---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
    - direction: Vertical
      body: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 2
      run:
        plugin:
          location: "zellij:status-bar"
tabs:
  - name: "Development"
    direction: Vertical
    run:
      command: {cmd: zsh, args: ["-c", "cd ~/Documents/development && zsh"]}
  - name: "Run/Debug"
    direction: Vertical
    run:
      command: {cmd: zsh, args: ["-c", "cd ~/Documents/development && zsh"]}
  - name: "Configuration"
    direction: Vertical
    run:
      command: {cmd: zsh, args: ["-c", "cd ~/.config && zsh"]}
  - name: "Scratchpad"
    direction: Vertical
  - name: "Music"
    direction: Vertical
    focus: true
    run:
      command: {cmd: ncspot}
